### ISSUE TITLE
Argo latest version

### ISSUE THREAD

**Issue by delucca** [runoncloud/terraform-kubernetes-argocd#1]
Hey :)

Great module! I'm planning to use it in my company's infrastructure.

Do you guys, by any chance, are planning to add the latest ArgoCD version? (1.7.7)

**Comment by jeanpbond** [comment]
Hey!

Thanks for your feedback. The new version is now compatible with all versions of ArgoCD and support the HA installation, but you'll need to upgrade to Terraform 0.13 if you haven't already ;).
